package hibernate;
// Generated 29 nov. 2013 17:00:48 by Hibernate Tools 3.6.0


import java.util.Date;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * PsCustomer generated by hbm2java
 */
@XmlRootElement
public class PsCustomer  implements java.io.Serializable {


     private Integer idCustomer;
     private int idGender;
     private int idDefaultGroup;
     private String firstname;
     private String lastname;
     private String email;
     private String passwd;
     private Date lastPasswdGen;
     private Date birthday;
     private boolean newsletter;
     private String ipRegistrationNewsletter;
     private Date newsletterDateAdd;
     private boolean optin;
     private String secureKey;
     private String note;
     private boolean active;
     private boolean isGuest;
     private boolean deleted;
     private Date dateAdd;
     private Date dateUpd;

    public PsCustomer() {
    }

	
    public PsCustomer(int idGender, int idDefaultGroup, String firstname, String lastname, String email, String passwd, Date lastPasswdGen, boolean newsletter, boolean optin, String secureKey, boolean active, boolean isGuest, boolean deleted, Date dateAdd, Date dateUpd) {
        this.idGender = idGender;
        this.idDefaultGroup = idDefaultGroup;
        this.firstname = firstname;
        this.lastname = lastname;
        this.email = email;
        this.passwd = passwd;
        this.lastPasswdGen = lastPasswdGen;
        this.newsletter = newsletter;
        this.optin = optin;
        this.secureKey = secureKey;
        this.active = active;
        this.isGuest = isGuest;
        this.deleted = deleted;
        this.dateAdd = dateAdd;
        this.dateUpd = dateUpd;
    }
    public PsCustomer(int idGender, int idDefaultGroup, String firstname, String lastname, String email, String passwd, Date lastPasswdGen, Date birthday, boolean newsletter, String ipRegistrationNewsletter, Date newsletterDateAdd, boolean optin, String secureKey, String note, boolean active, boolean isGuest, boolean deleted, Date dateAdd, Date dateUpd) {
       this.idGender = idGender;
       this.idDefaultGroup = idDefaultGroup;
       this.firstname = firstname;
       this.lastname = lastname;
       this.email = email;
       this.passwd = passwd;
       this.lastPasswdGen = lastPasswdGen;
       this.birthday = birthday;
       this.newsletter = newsletter;
       this.ipRegistrationNewsletter = ipRegistrationNewsletter;
       this.newsletterDateAdd = newsletterDateAdd;
       this.optin = optin;
       this.secureKey = secureKey;
       this.note = note;
       this.active = active;
       this.isGuest = isGuest;
       this.deleted = deleted;
       this.dateAdd = dateAdd;
       this.dateUpd = dateUpd;
    }
   
    public Integer getIdCustomer() {
        return this.idCustomer;
    }
    
    public void setIdCustomer(Integer idCustomer) {
        this.idCustomer = idCustomer;
    }
    public int getIdGender() {
        return this.idGender;
    }
    
    public void setIdGender(int idGender) {
        this.idGender = idGender;
    }
    public int getIdDefaultGroup() {
        return this.idDefaultGroup;
    }
    
    public void setIdDefaultGroup(int idDefaultGroup) {
        this.idDefaultGroup = idDefaultGroup;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPasswd() {
        return this.passwd;
    }
    
    public void setPasswd(String passwd) {
        this.passwd = passwd;
    }
    public Date getLastPasswdGen() {
        return this.lastPasswdGen;
    }
    
    public void setLastPasswdGen(Date lastPasswdGen) {
        this.lastPasswdGen = lastPasswdGen;
    }
    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }
    public boolean isNewsletter() {
        return this.newsletter;
    }
    
    public void setNewsletter(boolean newsletter) {
        this.newsletter = newsletter;
    }
    public String getIpRegistrationNewsletter() {
        return this.ipRegistrationNewsletter;
    }
    
    public void setIpRegistrationNewsletter(String ipRegistrationNewsletter) {
        this.ipRegistrationNewsletter = ipRegistrationNewsletter;
    }
    public Date getNewsletterDateAdd() {
        return this.newsletterDateAdd;
    }
    
    public void setNewsletterDateAdd(Date newsletterDateAdd) {
        this.newsletterDateAdd = newsletterDateAdd;
    }
    public boolean isOptin() {
        return this.optin;
    }
    
    public void setOptin(boolean optin) {
        this.optin = optin;
    }
    public String getSecureKey() {
        return this.secureKey;
    }
    
    public void setSecureKey(String secureKey) {
        this.secureKey = secureKey;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }
    public boolean isIsGuest() {
        return this.isGuest;
    }
    
    public void setIsGuest(boolean isGuest) {
        this.isGuest = isGuest;
    }
    public boolean isDeleted() {
        return this.deleted;
    }
    
    public void setDeleted(boolean deleted) {
        this.deleted = deleted;
    }
    public Date getDateAdd() {
        return this.dateAdd;
    }
    
    public void setDateAdd(Date dateAdd) {
        this.dateAdd = dateAdd;
    }
    public Date getDateUpd() {
        return this.dateUpd;
    }
    
    public void setDateUpd(Date dateUpd) {
        this.dateUpd = dateUpd;
    }




}


