<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="DWHWebServiceServiceWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/DWHWebServiceServiceWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/DWHWebServiceServiceWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://ws/">
    <import location="DWHWebApplication/wsdl/DWHWebServiceService.wsdl" namespace="http://ws/"/>
    <plnk:partnerLinkType name="DWHWebServiceLinkType">
        <plnk:role name="DWHWebServiceRole" portType="ns:DWHWebService"/>
    </plnk:partnerLinkType>
</definitions>

